#!/bin/bash

# During AWS EC2 instantiation (Debian image), the script to supply to
# "Advanced details" > "User data" to install packages required to run
# multi-threaded `transduce` benchmarks.

# Note: Packages take a few moments to download and install; they may
# not be available immediately after connecting to new instance.

set -eu

sudo apt-get -y update
sudo apt-get -y install openjdk-25-jdk
sudo apt-get -y install leiningen
sudo apt-get -y install git

exit 0

