#!/bin/bash

# Attempt to minimize benchmark variance by explicitly setting CPU affinity.

set -eu

taskset --cpu-list 3 lein with-profiles default,benchmark run -m brokvolli.performance.measure-range/do-measurements :quick

exit 0

