(ns brokvolli.performance.measure-utilities
  "Measure memory and time requirements."
  (:require
   [clojure.java.io :as io]
   [clojure.math :as math]
   [clojure.pprint :as pp]
   [clojure.set :as set]
   [clojure.string :as str]
   [clj-memory-meter.core :as mm]
   [criterium.core :as crit]))


(defn pow-10
  "Returns a vector of `[10^0 10^1 10^2 ... 10^n]` inclusive."
  {:UUIDv4 #uuid "29fca869-4355-4970-b944-13f803eb5ffc"}
  [n]
  (mapv #(long (math/pow 10 %)) (range (inc n))))


(defn measure-memory-one
  "Given function `f` that constructs a data structure of length 10^`n`, returns
  the memory size in bytes."
  {:UUIDv4 #uuid "d8dcea29-a86b-459a-a7fe-d15776504f51"}
  [f n]
  (mm/measure (f n) :bytes true :shallow false))


(defn measure-memory-fn
  "Given function `f` and max size 10^`n`, returns a hash-map of `n` associtated
  to memory size in bytes."
  {:UUIDv4 #uuid "acae133b-a8df-4125-8101-0cd2161a30fb"}
  [f max-len]
  (reduce #(assoc %1 %2 (measure-memory-one f %2)) {} (pow-10 max-len)))


(defn fn-obj-to-str
  "Given function object `fn-obj`, returns a str loadable by the edn reader."
  {:UUIDv4 #uuid "b810e93d-f8c0-4e42-a921-0ce05c8af656"}
  [fn-obj]
  (-> fn-obj
      type
      str
      (str/replace #"class " "")
      (str/replace #"\$" "/")))


(defn measure-memory-seq
  "Given sequential of functions `fns` and max size 10^`n`, returns a hash-map
  of function objects associated to memory measurement results."
  {:UUIDv4 #uuid "b4bcb56a-ed7b-4d51-ae25-7bb87380f624"}
  [fns max-len]
  (reduce #(assoc %1 (fn-obj-to-str %2) (measure-memory-fn %2 max-len)) {} fns))


(defn pretty-print-to-file
  "Writes `content` to file `filepath` with Clojure's pretty-printer."
  {:UUIDv4 #uuid "c205183a-fa6b-4581-bd58-3e22a66d44b0"
   :no-doc true}
  [filepath content]
  (binding [pp/*print-pretty* true
            pp/*print-miser-width* 40
            pp/*print-right-margin* 72
            *print-length* nil]
    (with-open [writer (io/writer filepath)]
      (pp/pprint content writer))))


(def ^{:dynamic true}
  *lightning-benchmark-opts*
  (reduce (fn [m k] (update m k #(/ % 2)))
          crit/*default-quick-bench-opts*
          [:max-gc-attempts
           :samples
           :target-execution-time
           :warmup-jit-period]))


(defn do-memory-measurements
  "Perform memory measurements and save results to file."
  {:UUIDv4 #uuid "461f3345-1ceb-4ae1-9562-6aa38c238173"}
  [fns max-len output-path-fname]
  (let [memory-measurements (measure-memory-seq fns max-len)]
    (pretty-print-to-file output-path-fname memory-measurements)))


(def ^{:no-doc true}
  thoroughnesses {:default crit/*default-benchmark-opts*
                  :quick crit/*default-quick-bench-opts*
                  :lightning *lightning-benchmark-opts*})


(defn dissoc-identifying-metadata
  "Given `metadata` hashmap  generated by Criterium benchmarking, dissociate
  key-vals from metadata that might be personally identifying information or
  enable fingerprinting, etc."
  {:UUIDv4 #uuid "eb6de892-6749-4092-8f0a-5e0d0852e94f"
   :no-doc true}
  [metadata]
  (let [remove-paths [[:runtime-details :vm-version]
                      [:runtime-details :name]
                      [:runtime-details :java-runtime-version]
                      [:runtime-details :input-arguments]]
        dissoc-in (fn [m p] (update-in m (butlast p) dissoc (last p)))]
    (reduce dissoc-in metadata remove-paths)))


(defn run-one-benchmark
  "Given function `f` and max size 10^`n`, run one benchmark with
  `thoroughness`, one of `:default`, `:quick`, or `:lightning`."
  {:UUIDv4 #uuid "d6c2e36a-ca1e-4bdb-94f2-41b03ab426e1"}
  [f n thoroughness]
  (crit/benchmark (f n) (thoroughnesses thoroughness)))


(defn date
  "Returns a hash-map of `:year`, `:month`, and `:date`, values all integers."
  {:UUIDv4 #uuid "a616d3ac-a297-4f61-a8b5-105c633d7a20"}
  []
  (let [crude (bean (java.util.Date.))
        filtered (select-keys (into (array-map) crude) [:year :month :date])]
    (-> filtered
        (update :year #(+ % 1900))
        (update :month inc)
        (set/rename-keys {:date :day}))))


(defn measure-time-fn
  "Given a function `f`, max size 10^`n`, and `thoroughness`, returns a hash-map
  of lengths associated to Criterium benchmark results."
  {:UUIDv4 #uuid "1dad5fc0-9590-4e4d-afb7-e076043df8b5"}
  [f max-len thoroughness]
  (reduce #(assoc %1 %2
                  (-> (run-one-benchmark f %2 thoroughness)
                      (assoc :metadata {:date (date)})
                      (assoc :results ::results-elided)
                      (dissoc-identifying-metadata)))
          {}
          (pow-10 max-len)))


(defn measure-time-seq
  "Given sequential of functions `fns`, max size 10^`n` and benchmark
  `thoroughness`, returns a hash-map of function object string renderings,
  associated to Criterium benchmark results, measured with `thoroughness`."
  {:UUIDv4 #uuid "6f7a2495-7d4d-474c-84cd-0e149acbc069"}
  [fns max-len thoroughness]
  (let [red-fn (fn [m v] (assoc m
                                (fn-obj-to-str v)
                                (measure-time-fn v max-len thoroughness)))]
    (reduce red-fn {} fns)))


(defn do-benchmarks
  "Perform performance benchmarks and save results to file. `fns` is a
  sequential of functions, `max-len` is the size of the largest argument in
  10^`max-len`, `fname` is the output file-pathname, and optional Criterium
  `thoroughness` is one of `:default`, `:quick`, or `:lightning`."
  {:UUIDv4 #uuid "27ce5721-ee74-44ff-8098-266de411de61"}
  ([fns max-len fname] (do-benchmarks fns max-len fname :default))
  ([fns max-len fname thoroughness]
   (let [time-measurements (measure-time-seq fns max-len thoroughness)]
     (pretty-print-to-file fname time-measurements))))

